### ISSUE TITLE
Aidlux桌面初始化失败。VIVO 和华为商店渠道安装两个设备都失败。

### ISSUE THREAD

**Issue by forhonourlx** [aidlearning/AidLearning-FrameWork#237]
请开发团队看看，HELP：

AIDLUX APP第一次启动后提示初始化失败的，桌面进不去。
然后命令`aid install aid-desktop`安装失败。。。
```
Preparing to unpack .../aid-desktop_1.5.1_arm64.deb ...
Unpacking aid-desktop (1.5.1) over (1.5.1) ...
Uninstalled successfully!
 will return to terminal
Traceback (most recent call last):
  File "/usr/local/bin/return_terminal", line 2, in <module>
    import android
  File "/usr/local/lib/python3.7/dist-packages/android.py", line 21, in <module>
    ap_port_f=open('/etc/opt/aidlux/ap_port','r')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/opt/aidlux/ap_port'
dpkg: warning: old aid-desktop package post-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
Uninstalled successfully!
 will return to terminal
Traceback (most recent call last):
  File "/usr/local/bin/return_terminal", line 2, in <module>
    import android
  File "/usr/local/lib/python3.7/dist-packages/android.py", line 21, in <module>
    ap_port_f=open('/etc/opt/aidlux/ap_port','r')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/opt/aidlux/ap_port'
dpkg: error processing archive /tmp/sys-279be4d8-b13b-4455-9daa-6f95fd87b543/aid-desktop_1.5.1_arm64.deb (--install):
 new aid-desktop package post-removal script subprocess returned error exit status 1
Uninstalled successfully!
 will return to terminal
Traceback (most recent call last):
  File "/usr/local/bin/return_terminal", line 2, in <module>
    import android
  File "/usr/local/lib/python3.7/dist-packages/android.py", line 21, in <module>
    ap_port_f=open('/etc/opt/aidlux/ap_port','r')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/opt/aidlux/ap_port'
dpkg: error while cleaning up:
 new aid-desktop package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 /tmp/sys-279be4d8-b13b-4455-9daa-6f95fd87b543/aid-desktop_1.5.1_arm64.deb
```

**Comment by forhonourlx** [comment]
@aidlearning Please Help.

**Comment by tangzeyu7** [comment]
提示进入error模式么?说下设备具体型号和Android版本呐

**Comment by forhonourlx** [comment]
> 提示进入error模式么?说下设备具体型号和Android版本呐

VIVO X100 PRO
![2c6d7e10d7c057f513d5abca3ab0c8c](https://github.com/aidlearning/AidLearning-FrameWork/assets/16576219/8eac77b8-f42e-4ebf-b7b5-9613b787df33)

进入应用后开不桌面，且aid-desktop也安装失败：
![46014555f8868892015237081624ae0](https://github.com/aidlearning/AidLearning-FrameWork/assets/16576219/77091919-45da-4c36-b692-ed7a1daf7f5d)

**Comment by tangzeyu7** [comment]
是Android14导致的系统服务启动失败,正在适配中

**Comment by iyangzh** [comment]
> 是Android14导致的系统服务启动失败,正在适配中

现在是五月，还没适配麻，我也遇到了同样的问题
