### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by xiaonaoer** [aidlearning/AidLearning-FrameWork#47]
```
FaceRecognition Init Finished.
Traceback (most recent call last):
  File "faceID.py", line 139, in <module>
    run_single_camera(url,'30.207.67.186')
  File "faceID.py", line 116, in run_single_camera
    q = Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

**Comment by aidlearning** [comment]
https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

**Comment by TuringZhai** [comment]
This ' url ' ,I tried today, but it didn't work.（rk3399）
Process the Queue using distributed processes

**Comment by aidlearning** [comment]
The reason is that users do not have read and write access to shared memory (/ dev / shm), but if you want write the / dev / shm , you need root access...

**Comment by aidlearning** [comment]
So the simplest way is to use a single thread. In fact, in Python language, multithreading is not really multithreading. If multithreading is needed, it is better to compile it into so library for calling

**Comment by TuringZhai** [comment]
multiprocessing.managers is not multithreading
