### ISSUE TITLE
How can I install AidLearning framework in my Jetson Nano Linux desktop?

### ISSUE THREAD

**Issue by BradleyWang123** [aidlearning/AidLearning-FrameWork#58]
When I run the faceID routie in my Jetson Nano Linux Desktop(ubuntu18.04 LTS),  I found  below error, I suspect I don't properly install AidLearning framework so that it can't connect to the usb camera( /dev/video1 ) to cause connection time out.

`$/src/facencnn/python3 faceID.py`
remi.server      INFO     Started httpserver http://0.0.0.0:5000/
remi.server.ws   INFO     connection established: ('127.0.0.1', 56134)
remi.request     INFO     built UI (path=/)
127.0.0.1 - - [10/Oct/2019 09:44:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2019 09:44:35] "GET /res:style.css HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 56146)
remi.server.ws   INFO     handshake complete
remi.server.ws   INFO     connection established: ('127.0.0.1', 56148)
remi.server.ws   INFO     handshake complete
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "faceID.py", line 48, in process
    cap = cvs.VideoCapture(0)
  File "/home/jetson/Documents/src/facencnn/cvs.py", line 64, in VideoCapture
    urlopen('http://172.0.0.1:9000/?name=aidcam' + str(camid))
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

remi.server.ws   INFO     connection established: ('127.0.0.1', 56184)
remi.server.ws   INFO     handshake complete

![Screenshot_2019-10-10 MyApp](https://user-images.githubusercontent.com/42103111/66533330-235bcb80-eb45-11e9-9c33-ca4b3be51376.png)
@qidiso @aidlearning @Yoline777

**Comment by aidlearning** [comment]
Sorry for later reply... because the aidlearning port is app,so you must install the apk in the android os...but the aidlux can run in the arm from the theory...but need modified something to fixing the linux different version....

**Comment by aidlearning** [comment]
In fact, we have started aidlearning running on arm Linux, but we will restart a project called aidlux, which will take some time to release.

**Comment by BradleyWang123** [comment]
Great! I feel it is convenient that programing and running python in the android phone or pad... but at the application level, it must be deploy to other platforms, waiting for your further good news!
